server {
    listen 80;
    listen [::]:80;
    server_name 87.120.187.186;

    location = /test_1 { return 301 /test_1/; }
    location = /test_2 { return 301 /test_2/; }
    location = /test_3 { return 301 /test_3/; }
    location = /test_4 { return 301 /test_4/; }
    location = /test_5 { return 301 /test_5/; }

    location /test_1/ {
        alias /var/www/cloudstaking/test_1/;
        index index.html;
    }

    location /test_2/ {
        alias /var/www/cloudstaking/;
        index index.html;
    }

    location /test_3/ {
        alias /var/www/cloudstaking/archive_test_3/;
        index index.html;
    }

    location /test_4/ {
        alias /var/www/cloudstaking/archive_test_4/;
        index index.html;
    }

    location /test_5/ {
        alias /var/www/cloudstaking/archive_test_5/;
        index index.html;

        location ~ ^/test_5/data/ {
            deny all;
            return 404;
        }

        location ~ ^/test_5/(.+\.php)$ {
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME /var/www/cloudstaking/archive_test_5/$1;
            fastcgi_pass unix:/run/php/php8.3-fpm.sock;
        }
    }

    location = / {
        return 302 /test_2/;
    }
}
